version: "3"

services:
  chat:
    build: .
    container_name: chat
    ports:
      - 8501:8501
    restart: always
    volumes:
      - ./configs/model_config.py:/Langchain-Chatchat/configs/model_config.py
    env_file:
      - .env
